name: Sisipkan blog

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g github-blog-zen
      - run: blog
      - uses: EndBug/add-and-commit@v7
        with:
          message: "tambahkan blog di readme"
          default_author: github_actions
          branch: master
